- name: Configuration of httpd.conf file
  template:
     src: httpd_conf.j2
     dest: /etc/httpd/conf/httpd.conf
  notify:
     - restart httpd service
- name: Creation of html files
  copy: src="index.html" dest="/var/www/html/index.html"
